# Generated by Django 4.2.7 on 2023-12-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
